### ISSUE TITLE
Error message when the field is in an entry.

### ISSUE THREAD

**Issue by PaulCWoods** [pixelandtonic/StoreHours#12]
Hi. Everything seems to have installed correctly, though getting this error when on the entry page with the Store Hours field
![screen shot 2017-04-21 at 18 17 12](https://cloud.githubusercontent.com/assets/2347534/25288845/0d60d7f0-26bf-11e7-955a-11937eb6a571.png)
Is this a known issue?

**Comment by MakeilaLundy** [comment]
having problems reproducing this. Can you send a zip of your `craft/storage/runtime/logs` files, a database dump to support@craftcms.com and exact steps to reproduce the problem so we can look into it some more.

Thanks

**Comment by takobell** [comment]
@PaulCWoods was able to track this down and fix it in https://github.com/pixelandtonic/StoreHours/releases/tag/1.2.1
