### ISSUE TITLE
Outputting the times doesn't respect the timezone set in Settings->General

### ISSUE THREAD

**Issue by takobell** [pixelandtonic/StoreHours#3]
https://craftcms.stackexchange.com/questions/6575/timezone-in-store-hours-plugin

**Comment by asalisbury** [comment]
I fixed this by passing `'UTC'` as the second argument into the `DateTime::createFromString();` functions found in the plugin's `StoreHoursFieldType.php` file. If you look at DateTime@createFromString you'll see it sets the default timezone to the one set in Craft's settings: `$timezone = craft()->getTimeZone();`... Admittedly, I've only had a cursory look at this, but it looks like it's shifting from UTC time twice: once in DateTime@createFromString and again in Twig's date() filter. So, explicitly passing 'UTC' prevents this double-shift from happening (I think...).

**Comment by pixelbeatcreative** [comment]
Is there a way to force it NOT to respect the timezone in settings? I'm using this as part of a front entry form and when a user enters their open/close time in the form, Craft automatically records the time according to my settings timezone which is UTC-4. I don't want that to happen. I need it to just record the exact time the user enters on the form. Is there a way to fix this?

**Comment by pixelbeatcreative** [comment]
Is there a way to force it NOT to respect the timezone in settings? I'm using this as part of a front entry form and when a user enters their open/close time in the form, Craft automatically records the time according to my settings timezone which is UTC-4. I don't want that to happen. I need it to just record the exact time the user enters on the form. Is there a way to fix this?
