### ISSUE TITLE
Leading Zeroes

### ISSUE THREAD

**Issue by smockensturm** [pixelandtonic/StoreHours#9]
We're getting leading zeroes on hours for either of these:

> {{ dayHours.open|date('h:i a') }}
> {{ dayHours.open|date('H:i a') }}

**Comment by takobell** [comment]
Use `g` https://secure.php.net/manual/en/function.date.php.  FFR usage questions should be posted on the Craft Stack Exchange site: https://craftcms.stackexchange.com/
